### ISSUE TITLE
RuntimeBinderException when trying to save file

### ISSUE THREAD

**Issue by crwxaj** [Zalunda/FunscriptToolbox#1]
This tool is a godsend to finally match old NAVR scripts to their remasters.

Alas I can't get it to work. I've tried it with this script: https://discuss.eroscripts.com/t/naughtyamericavr-remy-lacroix-assercise/71615

I created the asig files for the original and remastered video. But when I try to synchronize the funscript I get this error:

```
C:\code\FunscriptToolbox>FunscriptToolbox.exe as.cfs -a V:\NaughtyAmericaVR\amremyxander_vrdesktophd.asig -n V:\NaughtyAmericaVR\amremyxanderrem_6kvr265.asig -s "U:\EroScripts\ViritasViritae\Remy LaCroix - Xander Covus - AssErcise - NAVR.funscript"
Loading source funscript 'U:\EroScripts\ViritasViritae\Remy LaCroix - Xander Covus - AssErcise - NAVR.funscript'...
Loading audio signature from 'V:\NaughtyAmericaVR\amremyxander_vrdesktophd.asig'...
Loading audio signature from 'V:\NaughtyAmericaVR\amremyxanderrem_6kvr265.asig'...
Comparing audio signatures...

Generating actions synchronized to the second file...
   From 00:00:00     to 00:00:04.942,     0 actions have been DROPPED
   From 00:00:04.942 to 00:30:56.950,  4361 actions have been MOVED by -00:00:04.942
Saving synchronized version 'V:\NaughtyAmericaVR\amremyxanderrem_6kvr265.funscript'.
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at FunscriptToolbox.Funscript.AddNotes(String newNote)
   at FunscriptToolbox.AudioSyncVerbs.VerbAudioSyncCreateFunscript.Execute()
   at FunscriptToolbox.Program.<>c.<Main>b__2_1(Options options)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 notParsedFunc)
   at FunscriptToolbox.Program.Main(String[] args)```

**Comment by Zalunda** [comment]
Thanks for the report. 
It's because the original .funscript file didn't include a metadata section. 
Should be fixed in 1.0.2.

(and thanks for your work on XBVR, took me a minute to remember where I saw you handle)
